events {}

http {

    upstream llm_backend {
        server llm1:8000;
        server llm2:8000;
        server llm3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://llm_backend;
        }
    }

}
